-- ============================================================
-- AgroMap — Esquema completo para Supabase (PostgreSQL)
-- Generado a partir del modelo de datos de la aplicación React
-- ============================================================

-- 0. Extensiones
create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";

-- 1. Tipos enumerados
create type tipo_persona as enum ('madre cabeza de hogar', 'Adulto mayor', 'viuda');
create type tipo_visita as enum ('visita', 'seguimiento', 'capacitacion');

-- 2. Tabla: sectores (catálogo)
create table if not exists sectores (
  id    bigint generated by default as identity primary key,
  nombre text not null unique,
  lat_base double precision not null,
  lng_base double precision not null
);

comment on table sectores is 'Catálogo de veredas/sectores con coordenadas base';

insert into sectores (nombre, lat_base, lng_base) values
  ('El Municipio',                    1.2035, -76.9190),
  ('Vereda Bellavista',               1.2380, -76.9420),
  ('Vereda Cabrera',                  1.1820, -76.9050),
  ('Vereda Cabuyayaco',              1.1700, -76.9280),
  ('Vereda Campoalegre',             1.2100, -76.9160),
  ('Vereda El Cedro',                1.2000, -76.9300),
  ('Vereda El Ejido',                1.1830, -76.9250),
  ('Vereda Fátima Carrizayaco',      1.1980, -76.9050),
  ('Vereda La Cumbre',               1.1950, -76.8950),
  ('Vereda Las Cochas',              1.1720, -76.9180),
  ('Vereda Leandro Agreda',          1.1580, -76.9350),
  ('Vereda Llano Grande',            1.1680, -76.9380),
  ('Vereda Machindinoy',             1.1950, -76.9250),
  ('Vereda Palmas',                  1.1880, -76.9350),
  ('Vereda Sagrado Corazón de Jesús',1.1870, -76.9200),
  ('Vereda San Félix Sinsayaco',     1.1660, -76.9150),
  ('Vereda San José la Hidráulica',  1.2060, -76.9080),
  ('Vereda Tamabioy',                1.1750, -76.8980),
  ('Vereda Villaflor',               1.2150, -76.9250)
on conflict (nombre) do nothing;

-- 3. Tabla principal: asociadas
create table if not exists asociadas (
  id                bigint generated by default as identity primary key,
  nombre            text not null,
  edad              integer check (edad > 0 and edad < 120),
  telefono          text,
  num_personas      integer default 1 check (num_personas > 0),
  sector_id         bigint references sectores(id) on delete set null,
  area_huerta       text,
  productos         text,
  fecha_siembra     date,
  fecha_ultima_visita date,
  num_visitas       integer default 0 check (num_visitas >= 0),
  tipo_persona      tipo_persona,
  observaciones     text,
  lat               double precision,
  lng               double precision,
  creado_en         timestamptz not null default now(),
  actualizado_en    timestamptz not null default now()
);

comment on table asociadas is 'Productoras/es asociadas al programa de huertas';

create index idx_asociadas_sector_id on asociadas(sector_id);
create index idx_asociadas_tipo_persona on asociadas(tipo_persona);
create index idx_asociadas_coords on asociadas(lat, lng);
create index idx_asociadas_fecha_ultima_visita on asociadas(fecha_ultima_visita);
create index idx_asociadas_nombre_trgm on asociadas using gin (nombre gin_trgm_ops);

-- 4. Tabla: visitas / seguimiento
create table if not exists visitas (
  id              bigint generated by default as identity primary key,
  asociada_id     bigint not null references asociadas(id) on delete cascade,
  fecha           date not null default current_date,
  tipo            tipo_visita not null default 'visita',
  observaciones   text,
  proxima_visita  date,
  creado_en       timestamptz not null default now(),
  actualizado_en  timestamptz not null default now()
);

comment on table visitas is 'Registro de visitas, seguimientos y capacitaciones';

create index idx_visitas_asociada_id on visitas(asociada_id);
create index idx_visitas_fecha on visitas(fecha);
create index idx_visitas_tipo on visitas(tipo);
create index idx_visitas_proxima on visitas(proxima_visita)
  where proxima_visita is not null;

-- 5. Trigger: actualizar updated_at automáticamente
create or replace function trigger_set_updated_at()
returns trigger as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_asociadas_updated_at
  before update on asociadas
  for each row execute function trigger_set_updated_at();

create trigger trg_visitas_updated_at
  before update on visitas
  for each row execute function trigger_set_updated_at();

-- 6. Trigger: mantener num_visitas y fecha_ultima_visita en asociadas
create or replace function sync_asociada_visita_stats()
returns trigger as $$
begin
  if tg_op = 'INSERT' then
    update asociadas
    set num_visitas = num_visitas + 1,
        fecha_ultima_visita = greatest(fecha_ultima_visita, new.fecha)
    where id = new.asociada_id;
    return new;
  elsif tg_op = 'DELETE' then
    update asociadas
    set num_visitas = num_visitas - 1
    where id = old.asociada_id;
    return old;
  elsif tg_op = 'UPDATE' and old.asociada_id != new.asociada_id then
    update asociadas set num_visitas = num_visitas - 1 where id = old.asociada_id;
    update asociadas set num_visitas = num_visitas + 1 where id = new.asociada_id;
    return new;
  end if;
  return null;
end;
$$ language plpgsql;

create trigger trg_visitas_sync_asociada
  after insert or delete on visitas
  for each row execute function sync_asociada_visita_stats();

-- 7. Vista: alertas para el panel admin
create or replace view alertas_asociadas as
select
  a.id,
  a.nombre,
  a.sector_id,
  s.nombre as sector,
  a.tipo_persona,
  a.fecha_ultima_visita,
  a.num_visitas,
  extract(day from (now() - a.fecha_ultima_visita))::int as dias_sin_visita,
  case
    when a.fecha_ultima_visita is null then true
    when extract(day from (now() - a.fecha_ultima_visita)) > 30 then true
    else false
  end as alerta_sin_visita,
  case when a.num_visitas < 2 then true else false end as alerta_baja_frecuencia
from asociadas a
left join sectores s on s.id = a.sector_id;

-- 8. Vista: estadísticas del dashboard
create or replace view stats_dashboard as
select
  count(*)                                         as total_asociadas,
  coalesce(sum(num_personas), 0)                   as total_beneficiarios,
  round(avg(edad)::numeric, 1)                     as edad_promedio,
  min(edad)                                        as edad_min,
  max(edad)                                        as edad_max,
  coalesce(sum(num_visitas), 0)                    as total_visitas,
  count(*) filter (where num_visitas > 0)          as activas,
  count(*) filter (where num_visitas = 0)          as inactivas,
  (select count(distinct sector_id) from asociadas where sector_id is not null) as total_sectores
from asociadas;

-- 9. Vista: próximas visitas programadas
create or replace view proximas_visitas as
select
  v.id,
  v.asociada_id,
  a.nombre as asociada_nombre,
  s.nombre as sector,
  v.fecha as ultima_visita,
  v.proxima_visita,
  v.tipo,
  v.observaciones,
  v.proxima_visita - current_date as dias_restantes
from visitas v
join asociadas a on a.id = v.asociada_id
left join sectores s on s.id = a.sector_id
where v.proxima_visita >= current_date
order by v.proxima_visita asc;

-- 10. Vista: resumen por sector
create or replace view stats_sectores as
select
  s.id,
  s.nombre,
  count(a.id)                                    as total_asociadas,
  coalesce(sum(a.num_personas), 0)               as total_beneficiarios,
  coalesce(sum(a.num_visitas), 0)                as total_visitas,
  round(coalesce(avg(a.num_visitas), 0)::numeric, 1) as visitas_promedio,
  count(*) filter (where a.num_visitas = 0)      as sin_visitas
from sectores s
left join asociadas a on a.sector_id = s.id
group by s.id, s.nombre
order by visitas_promedio asc;

-- 11. Función: días desde última visita
create or replace function dias_sin_visita(asociada_id bigint)
returns integer as $$
declare
  ultima date;
begin
  select max(fecha) into ultima from visitas where visitas.asociada_id = dias_sin_visita.asociada_id;
  if ultima is null then return 999; end if;
  return extract(day from (now() - ultima))::integer;
end;
$$ language plpgsql stable;

-- 12. Vista: distribución por edad
create or replace view distribucion_edad as
select
  case
    when edad between 18 and 25 then '18–25'
    when edad between 26 and 35 then '26–35'
    when edad between 36 and 45 then '36–45'
    when edad between 46 and 55 then '46–55'
    when edad between 56 and 65 then '56–65'
    when edad >= 66 then '66+'
  end as rango,
  count(*) as total
from asociadas
where edad is not null
group by rango
order by min(edad);

-- 13. Vista: tipos de visita más frecuentes
create or replace view stats_tipos_visita as
select
  tipo::text,
  count(*) as total,
  count(distinct asociada_id) as asociadas_unicas
from visitas
group by tipo
order by total desc;

-- ============================================================
-- 14. Seguridad: Row Level Security (RLS)
-- ============================================================
alter table sectores enable row level security;
alter table asociadas enable row level security;
alter table visitas enable row level security;

-- Políticas públicas de lectura para todos los usuarios autenticados
create policy "Sectores visible para todos"
  on sectores for select using (true);

create policy "Asociadas visible para todos"
  on asociadas for select using (true);

create policy "Visitas visible para todos"
  on visitas for select using (true);

-- Políticas de escritura (ajustar según el nivel de acceso deseado)
create policy "Asociadas insertable por autenticados"
  on asociadas for insert with check (auth.role() = 'authenticated');

create policy "Asociadas actualizable por autenticados"
  on asociadas for update using (auth.role() = 'authenticated');

create policy "Asociadas eliminable por autenticados"
  on asociadas for delete using (auth.role() = 'authenticated');

create policy "Visitas insertable por autenticados"
  on visitas for insert with check (auth.role() = 'authenticated');

create policy "Visitas actualizable por autenticados"
  on visitas for update using (auth.role() = 'authenticated');

create policy "Visitas eliminable por autenticados"
  on visitas for delete using (auth.role() = 'authenticated');
